import { defineField, defineType } from "sanity";

export const hero = defineType({
  name: "hero",
  title: "🏠 Hero Section (Homepage Top)",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "profile", title: "Profile" },
    { name: "cards", title: "Cards & video" },
    { name: "banner", title: "Top banner" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Your Name",
      type: "string",
      description: "Your full name as displayed in the hero section",
      validation: (Rule) => Rule.required(),
      group: "profile",
    }),
    defineField({
      name: "profileImage",
      title: "Profile Photo",
      type: "image",
      description:
        "📸 Your professional headshot photo (displayed as a circle)",
      options: {
        hotspot: true,
        accept: "image/*",
      },
      validation: (Rule) => Rule.required(),
      group: "profile",
    }),
    defineField({
      name: "title",
      title: "Old Headline (not shown)",
      type: "string",
      description: "No longer shown on the site. The hero now uses Greeting, Role and Intro Line.",
      hidden: ({ value }) => !value,
      group: "content",
    }),
    defineField({
      name: "description",
      title: "Old Description (not shown)",
      type: "text",
      rows: 6,
      description: "No longer shown on the site. The hero now uses Greeting, Role and Intro Line.",
      hidden: ({ value }) => !value,
      group: "content",
    }),
    defineField({
      name: "greeting",
      title: "Greeting",
      type: "string",
      description: "First line of the big headline, e.g. “Hi, I’m Srinidhi.”",
      initialValue: "Hi, I’m Srinidhi.",
      group: "content",
    }),
    defineField({
      name: "role",
      title: "Role",
      type: "string",
      description: "Second line of the headline, shown with a soft green fade.",
      initialValue: "Customer Success Career Coach.",
      group: "content",
    }),
    defineField({
      name: "intro",
      title: "Intro Line",
      type: "string",
      description:
        "The sentence under the headline. The Service Labels are added after it as clickable chips, e.g. “…with [Resume Writing], [LinkedIn Optimization] and [Coaching].”",
      group: "content",
    }),
    defineField({
      name: "ctaText",
      title: "Button Text",
      type: "string",
      description: "The main button. It scrolls visitors to the services/pricing section.",
      initialValue: "Find the Right Service",
      group: "content",
    }),
    defineField({
      name: "secondaryCtaText",
      title: "Second Button Text",
      type: "string",
      description: "Optional second button that scrolls to the free checklist.",
      group: "content",
    }),
    defineField({
      name: "serviceLabels",
      title: "Service Labels",
      type: "array",
      of: [{ type: "string" }],
      description:
        "Shown as chips at the end of the Intro Line. Each links to its section (labels mentioning Resume, LinkedIn or Coaching).",
      group: "content",
    }),
    defineField({
      name: "bannerEnabled",
      title: "Show Top Banner",
      type: "boolean",
      description: "The small floating banner above the navigation bar. Turn it off to hide it.",
      initialValue: true,
      group: "banner",
    }),
    defineField({
      name: "bannerText",
      title: "Banner Text",
      type: "string",
      description: "e.g. “Free checklist: see which of your skills already fit Customer Success.”",
      group: "banner",
    }),
    defineField({
      name: "bannerLinkText",
      title: "Banner Link Text",
      type: "string",
      description: "The bold link after the text, e.g. “Get it free”. Leave empty for no link.",
      group: "banner",
    }),
    defineField({
      name: "bannerLink",
      title: "Banner Link",
      type: "string",
      description: "A section on the page (e.g. #free-checklist) or a full URL.",
      initialValue: "#free-checklist",
      group: "banner",
    }),
    defineField({
      name: "introVideo",
      title: "Intro Video",
      type: "file",
      description: "A short video of you (MP4). Shown in the second card slot; a placeholder shows until you add one.",
      options: { accept: "video/mp4,video/webm,video/quicktime" },
      group: "cards",
    }),
    defineField({
      name: "introVideoPoster",
      title: "Video Cover Image",
      type: "image",
      description: "Optional still shown before the video plays.",
      group: "cards",
    }),
    defineField({
      name: "cards",
      title: "Cards",
      type: "array",
      description: "The tilted cards under the headline (three works best). The video sits between the first and second card.",
      group: "cards",
      validation: (Rule) => Rule.max(4),
      of: [
        {
          type: "object",
          name: "heroCard",
          fields: [
            defineField({ name: "title", title: "Title", type: "string", validation: (Rule) => Rule.required() }),
            defineField({ name: "text", title: "Text", type: "text", rows: 3 }),
            defineField({ name: "buttonText", title: "Button Text", type: "string" }),
            defineField({
              name: "buttonLink",
              title: "Button Link",
              type: "string",
              description: "A section on the page (e.g. #pricing) or a full URL.",
            }),
            defineField({
              name: "color",
              title: "Colour",
              type: "string",
              options: {
                list: [
                  { title: "Peach", value: "peach" },
                  { title: "Blush", value: "blush" },
                  { title: "Lavender", value: "lavender" },
                  { title: "Sky", value: "sky" },
                  { title: "Mint", value: "mint" },
                  { title: "Butter", value: "butter" },
                ],
                layout: "radio",
                direction: "horizontal",
              },
              initialValue: "peach",
            }),
          ],
          preview: { select: { title: "title", subtitle: "buttonText" } },
        },
      ],
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "title",
      media: "profileImage",
    },
  },
});
